# Site settings
title: Your awesome title
email: your-email@domain.com
description: "Freelance programmerer. Ta kontakt for hjelp til utvikling av web-l√∏sninger, apper, hjemmesider, etc."
baseurl: ""
url: "http://yourdomain.com"

# Build settings
markdown: kramdown
permalink: pretty
